name:                programming-in-haskell
version:             0.1.0.0
github:              "githubuser/programming-in-haskell"
license:             MIT
author:              "Oisín Mac Fhearaí"
maintainer:          "denpashogai@gmail.com"
copyright:           "2021 Oisín Mac Fhearaí"

extra-source-files:
- README.md

description:         Please see the README on GitHub at <https://github.com/DestyNova/exercises-programming-in-haskell#readme>

dependencies:
- base >= 4.7 && < 5

library:
  source-dirs: src

executables:
  programming-in-haskell-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -O2
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - programming-in-haskell

tests:
  programming-in-haskell-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - programming-in-haskell
    - hspec
